// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mcyfrcvymjlpwycktadn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1jeWZyY3Z5bWpscHd5Y2t0YWRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyMDIwNzUsImV4cCI6MjA1Nzc3ODA3NX0.nOqjkKKCxwMcBxPA_4s3XTNei4naDwMfgSRkt-qEH2g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);